# Site settings
last_updated: 12 jul 2018
title: 'josé r. pacheco | software'
title_abbrev: jrpache.co
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""

# Personal Info
author: José R. Pacheco
email: hi@jrpache.co
feedback_email: feedback@jrpache.co

# Build settings
markdown: kramdown
plugins:
  - jekyll-timeago
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea/