# Site settings
last_updated: 12 jul 2018
title: 'josé pacheco | software'
title_abbrev: jrpache.co
description: >- # this means to ignore newlines until "baseurl:"
  The official website of José Pacheco, senior software engineer at Numerator
baseurl: ""
url: ""

# Personal Info
author: José R. Pacheco
email: hi@jrpache.co
feedback_email: feedback@jrpache.co

# Build settings
markdown: kramdown
plugins:
  - jekyll-timeago
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea/
